Repository JNU-econovation/EEOS-BE, pull requests merged in 2024-07, with the labels that each got.

#84 [FEAT] 질문 기능 개발
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/CommandCommentResponse.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/CreateCommentRequest.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/QueryAnswerResponse.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/QueryCommentResponse.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/QueryCommentsResponse.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/UpdateCommentRequest.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/converter/CommentResponseConverter.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/DeniedEditCommentException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/ExceedContentLimitLengthException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/NotConvertedCommentException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/NotFoundCommentException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/UnExpectedNPException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/model/CommentModel.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/model/converter/CommentModelConverter.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/service/CommentService.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/usecase/CreateCommentUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/usecase/DeleteCommentUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/usecase/GetCommentUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/usecase/UpdateCommentUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/comment/persistence/CommentEntity.java
  eeos/src/main/java/com/blackcompany/eeos/comment/persistence/CommentRepository.java
  eeos/src/main/java/com/blackcompany/eeos/comment/persistence/converter/CommentEntityConverter.java
  eeos/src/main/java/com/blackcompany/eeos/comment/presentation/CommentController.java
Labels: feature

#88 [UPDATE] Team CRUD, 관리자 검사 로직 최적화
  eeos/src/main/java/com/blackcompany/eeos/member/application/model/MemberModel.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/model/Name.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/service/QueryMemberService.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/Service/TeamService.java
Labels: feature

#93 [FEAT] Program 3.0 기능 개발
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/CommandProgramRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/CreateProgramRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/UpdateProgramRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/converter/ProgramRequestConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/TeamPresentService.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/PresentTeamUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/PresentationEntity.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/PresentationRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/converter/PresentationConverter.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/Service/TeamService.java
Labels: feature

#94 [FEAT] Admin 계정 자동 생성 로직 추가
  eeos/src/main/java/com/blackcompany/eeos/auth/application/model/AccountEntityConverter.java
  eeos/src/main/java/com/blackcompany/eeos/auth/application/model/AccountModel.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/model/AdminInfo.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/model/Name.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/service/CreateAdminMemberService.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/usecase/CreateAdminMemberUsecase.java
  eeos/src/main/resources/application-admin.yml
Labels: feature

#96 [FEAT] application.yml 설정 추가
  eeos/src/main/java/com/blackcompany/eeos/auth/application/domain/converter/OauthMemberEntityConverter.java
  eeos/src/main/java/com/blackcompany/eeos/auth/persistence/OAuthMemberEntity.java
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/LoginConfig.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/model/CommentModel.java
  eeos/src/main/java/com/blackcompany/eeos/comment/persistence/converter/CommentEntityConverter.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/service/QueryMemberService.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClient.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClientImpl.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/dto/SlackChatPostMessageResponse.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/exception/SlackChatApiUnAuthException.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/mapper/ObjectToJsonMapper.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BotTokens.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ChatPostModelConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/support/ChannelGetter.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/support/TokenGetter.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/Service/TeamService.java
  eeos/src/main/resources/application.yml
Labels: feature

#98 [FIX] inner class Team -> static inner class Team 으로 변경
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/CreateProgramRequest.java
Labels: 🔧refactor

#100 [FIX] 팀 리스트 조회 기능을 보완합니다.
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/PresentationRepository.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/Service/TeamService.java
Labels: feature

#102 [FEAT] 행사 생성 시 관리자 권한 로직 추가
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/DeniedCommentEditException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/presentation/CommentController.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/exception/DeniedProgramEditException.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/Service/TeamService.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/exception/DeniedTeamEditException.java
Labels: feature

#106 [FIX] Comment 조회 오류를 해결합니다.
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/converter/CommentResponseConverter.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/NotExpectedCommentEditException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/service/CommentService.java
  eeos/src/main/java/com/blackcompany/eeos/comment/persistence/CommentRepository.java
Labels: 🔧refactor

#111 [FIX] 관리자 고멘트 작성 불가 및 대댓글 조회 오류 수정
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/converter/CommentResponseConverter.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/exception/NotCreateAdminCommentException.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/model/CommentModel.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/service/CommentService.java
Labels: 🔧refactor

#113 [FIX] 코멘트 수정 오류 해결
  eeos/src/main/java/com/blackcompany/eeos/comment/application/service/CommentService.java
Labels: 🔧refactor

#114 [FEAT] 출석체크 기능 로직 변경 및 멤버 조회 시 관리자 불 포함
  eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberEntity.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/CommandMemberController.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/AttendModeChangeUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/AttendStartUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/ChangeAttendStatusRequest.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/exception/DeniedChangeAttendException.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/model/AttendModel.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/ChangeAttendStatusUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/AttendController.java
Labels: feature, 🔧refactor

#117 [UPDATE] 출석하기 기능 HTTP Method 변경
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/AttendController.java
Labels: 🔧refactor

#118 [UPDATE] PostMapping import
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/AttendController.java
Labels: 🔧refactor

#120 [FEAT] oauth_member 삭제 로직 추가
  eeos/src/main/java/com/blackcompany/eeos/member/application/service/CommandMemberService.java
Labels: feature

#121 [FIX] CommandMemberService 수정
  eeos/docker-compose-local.yml
  eeos/src/main/java/com/blackcompany/eeos/member/application/service/CommandMemberService.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/usecase/ChangeActiveStatusUsecase.java
Labels: 🔧refactor

#122 [FIX] OauthMemberRepository 의존성 추가
  eeos/src/main/java/com/blackcompany/eeos/member/application/service/CommandMemberService.java
Labels: 🔧refactor

#124 [FEAT] 행사 종료 시 출석 체크도 자동 종료
  eeos/src/main/java/com/blackcompany/eeos/config/SchedulingConfig.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/CreateProgramRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramQuitService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/support/ProgramAttendScheduler.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/ProgramQuitUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/persistence/RedisDelayedQueue.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/event/EndAttendModeEvent.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/event/EndAttendModeEventListener.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/TeamPresentService.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendRepository.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/Service/TeamService.java
  eeos/src/main/java/com/blackcompany/eeos/team/application/exception/NotFoundTeamException.java
Labels: 🔧refactor

#125 [FEAT] NotFoundTeamException 수정
  eeos/src/main/java/com/blackcompany/eeos/team/application/exception/NotFoundTeamException.java
Labels: 🔧refactor
