Repository JNU-econovation/EEOS-BE, pull requests merged in 2024-04, with the labels that each got.

#31 [FEAT] Swagger API description 수정
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/controller/AuthController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/AttendController.java
Labels: feature

#40 [FEAT] 운영용, 개발용 docker-compose 파일을 분리한다
  eeos/docker-compose-dev.yml
  eeos/docker-compose-prod.yml
Labels: bug

#37 [UPDATE] Swagger description 수정
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/controller/AuthController.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/CommandMemberController.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/QueryMemberController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/AttendController.java
Labels: documentation, feature

#35 [FEAT] 게스트 모드 구현
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/LoginConfig.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/guest/GuestAccessRights.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/guest/GuestProgramController.java
Labels: feature

#42 [FEAT] Slack 알림에 필요한 자료구조 구현
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramNotificationModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/NotifyProgramUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/dto/ProgramSlackNotificationRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/dto/SlackNotificationRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BlockModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BlockTypes.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ChatPostModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/MessageModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ProgramMessageAnnouncements.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/TextModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/TextTypes.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ProgramSlackNotificationMessageConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
Labels: feature

#46 [REFACTOR] Slack Notification 리팩토링
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramNotificationModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ChatPostModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ChatPostModelConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
Labels: feature, 🔧refactor

#48 [UPDATE] GuestProgramController, ProgramController 새로운 API Swagger등록
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/guest/GuestProgramController.java
Labels: documentation

#44 [FEAT] Slack Api 호출 및 행사 생성자 불일치 예외 정의
  eeos/src/main/java/com/blackcompany/eeos/auth/infra/oauth/slack/client/SlackOauthApiClient.java
  eeos/src/main/java/com/blackcompany/eeos/auth/infra/oauth/slack/client/SlackOauthApiClientImpl.java
  eeos/src/main/java/com/blackcompany/eeos/auth/infra/oauth/slack/client/SlackOauthMemberClient.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/ProgramSlackNotificationRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/SlackNotificationRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/exception/DeniedProgramNotificationException.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramNotificationModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/NotifyProgramUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClient.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClientImpl.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/dto/SlackChatPostMessageResponse.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BotTokens.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/Channels.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ChatPostModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ChatPostModelConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/resources/application-slack.yml
  eeos/src/test/java/com/blackcompany/eeos/auth/infra/oauth/slack/client/FakeSlackApiClient.java
  eeos/src/test/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/FakeChatPostModel.java
Labels: feature

#50 [UPDATE] Spotless 적용 및 오타 수정
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/LoginConfig.java
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/controller/AuthController.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/CommandMemberController.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/QueryMemberController.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/ProgramSlackNotificationRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/SlackNotificationRequest.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/exception/DeniedProgramNotificationException.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramNotificationModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/NotifyProgramUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClient.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClientImpl.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/dto/SlackChatPostMessageResponse.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BlockModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BlockTypes.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BotTokens.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/Channels.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ChatPostModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/MessageModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ProgramMessageAnnouncements.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/TextModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/TextTypes.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ChatPostModelConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/guest/GuestAccessRights.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/guest/GuestProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/swagger/config/SwaggerConfig.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/AttendController.java
  eeos/src/main/resources/application-slack.yml
Labels: 🔧refactor

#51 [UPDATE] application-slack.yml 오타 수정
  eeos/src/main/resources/application-slack.yml
  eeos/src/main/resources/application.yml
Labels: 🔧refactor

#53 [REFACTOR] Slack Notification 코드를 수정합니다.
  eeos/src/main/java/com/blackcompany/eeos/program/application/exception/DeniedProgramNotificationException.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/exception/NotWeeklyProgramException.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClient.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClientImpl.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/config/FeignConfig.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/dto/SlackChatPostMessageResponse.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/exception/SlackChatApiUnAuthException.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/interceptor/SlackBCChatOpenFeignInterceptor.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/mapper/ObjectToJsonMapper.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BlockModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/BotTokens.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/Channels.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ChatPostModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/MessageModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/TextModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ChatPostModelConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/support/ChannelGetter.java
  eeos/src/main/resources/application-slack.yml
Labels: feature, 🔧refactor

#55 [FIX] OpenFeign을 재설정 합니다.
  eeos/src/main/java/com/blackcompany/eeos/config/ChatOpenFeignConfig.java
  eeos/src/main/java/com/blackcompany/eeos/config/GlobalOpenFeignConfig.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClientImpl.java
Labels: bug

#57 [UPDATE] 날짜 형식 및 멘트 일부 수정
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/ProgramMessageAnnouncements.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/converter/ChatPostModelConverter.java
Labels: 🔧refactor

#59 [UPDATE] Slack API 호출 코드를 수정합니다.
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/LoginConfig.java
  eeos/src/main/java/com/blackcompany/eeos/config/ChatOpenFeignConfig.java
  eeos/src/main/java/com/blackcompany/eeos/config/OpenFeignConfig.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClient.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/client/SlackChatApiClientImpl.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/interceptor/SlackBCChatOpenFeignInterceptor.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/model/Channels.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/support/TokenGetter.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  eeos/src/main/resources/application-slack.yml
Labels: 🔧refactor

#61 [FIX] Channel 오타를 수정합니다.
  eeos/src/main/java/com/blackcompany/eeos/program/infra/api/slack/chat/service/ProgramNotifyServiceComposite.java
Labels: bug

#63 [REMOVE] 외부 API 호출하는 컨트롤러 테스트 코드를 삭제합니다.
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
Labels: bug
