Repository JNU-econovation/EEOS-BE, pull requests merged in 2025-03, with the labels that each got.

#217 [FEAT] 출석 요약 정보 조회 기능 API 구현
  eeos/logs/2024-11-24/eeos.log
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramDateRangeService.java
  eeos/src/main/java/com/blackcompany/eeos/program/persistence/ProgramRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/AttendSummaryInfoResponse.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/AttendWeightPolicyApplicationDto.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/exception/NotFoundSignTypeException.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/model/AttendWeightPolicyModel.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/model/SignType.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendWeightCalculator.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendWeightPolicyService.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/support/AttendCountCalculate.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/CommandAttendWeightPolicyUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/GetAttendWeightPolicyUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/GetAttendantInfoUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendWeightPolicyEntity.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendWeightPolicyRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendWeightPolicyRepositoryImpl.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/JpaWeightPolicyRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/controller/AttendController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/controller/AttendWeightPolicyController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/docs/AttendApi.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/docs/AttendWeightPolicyApi.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/dto/AttendWeightPolicyWebDto.java
  eeos/src/test/java/com/blackcompany/eeos/target/application/service/AttendWeightPolicyServiceTest.java
Labels: feature

#224 [FEAT] 벌점 상위 Top 10 조회 기능 구현
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/LoginConfig.java
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/controller/AuthController.java
  eeos/src/main/java/com/blackcompany/eeos/auth/presentation/docs/AuthApi.java
  eeos/src/main/java/com/blackcompany/eeos/comment/presentation/controller/CommentController.java
  eeos/src/main/java/com/blackcompany/eeos/comment/presentation/docs/CommentApi.java
  eeos/src/main/java/com/blackcompany/eeos/common/exception/GlobalExceptionHandler.java
  eeos/src/main/java/com/blackcompany/eeos/common/exception/InvalidParameterException.java
  eeos/src/main/java/com/blackcompany/eeos/common/presentation/response/ApiResponse.java
  eeos/src/main/java/com/blackcompany/eeos/common/presentation/response/ApiResponseBody.java
  eeos/src/main/java/com/blackcompany/eeos/common/presentation/response/ApiResponseGenerator.java
  eeos/src/main/java/com/blackcompany/eeos/common/presentation/response/MessageCode.java
  eeos/src/main/java/com/blackcompany/eeos/common/presentation/response/PageResponse.java
  eeos/src/main/java/com/blackcompany/eeos/health/HealthController.java
  eeos/src/main/java/com/blackcompany/eeos/member/application/repository/MemberRepository.java
  eeos/src/main/java/com/blackcompany/eeos/member/persistence/JpaMemberCustomRepository.java
  eeos/src/main/java/com/blackcompany/eeos/member/persistence/JpaMemberRepository.java
  eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberRepositoryImpl.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/MemberController.java
  eeos/src/main/java/com/blackcompany/eeos/member/presentation/docs/MemberApi.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/converter/ProgramPageResponseConverter.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/exception/IsNotGithubUrlException.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramDateRangeService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramsUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/controller/GuestProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/controller/ProgramController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/docs/GuestProgramApi.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/docs/ProgramApi.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/AttendPenaltyResponse.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/AttendPenaltyResponses.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/PenaltyInfoRequest.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/converter/AttendPenaltyResponseConverter.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/repository/AttendRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/GetAttendantInfoUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/controller/AttendController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/controller/AttendWeightPolicyController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/controller/TeamBuildingTargetController.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/docs/AttendApi.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/docs/AttendWeightPolicyApi.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/docs/TeamBuildingTargetApi.java
  eeos/src/main/java/com/blackcompany/eeos/team/presetation/controller/TeamController.java
  eeos/src/main/java/com/blackcompany/eeos/team/presetation/docs/TeamApi.java
  eeos/src/main/java/com/blackcompany/eeos/teamBuilding/presentation/controller/TeamBuildingController.java
  eeos/src/main/java/com/blackcompany/eeos/teamBuilding/presentation/docs/TeamBuildingApi.java
  eeos/src/main/resources/application-swagger.yml
Labels: feature

#232 [FIX] 3개의 에러를 수정합니다.
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/QueryAnswerResponse.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/QueryCommentResponse.java
  eeos/src/main/java/com/blackcompany/eeos/comment/application/dto/converter/CommentResponseConverter.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/dto/AttendSummaryInfoResponse.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
  eeos/src/main/java/com/blackcompany/eeos/target/presentation/controller/AttendController.java
Labels: bug

#236 [FIX] MemberCustomRepository 수정
  eeos/src/main/java/com/blackcompany/eeos/member/persistence/JpaMemberCustomRepository.java
Labels: bug

#239 [FEAT] 캘린더(시작/종료)날짜 설정/조회
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/request/CalendarApplicationCommand.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/dto/response/CalendarPeriodApplicationQuery.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/model/CalendarModel.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/repository/CalendarRepository.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/service/CalendarService.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/support/CalendarProvider.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetCalendarUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/UpdateCalendarUsecase.java
  eeos/src/main/java/com/blackcompany/eeos/program/persistence/CalendarEntity.java
  eeos/src/main/java/com/blackcompany/eeos/program/persistence/CalendarRepositoryImpl.java
  eeos/src/main/java/com/blackcompany/eeos/program/persistence/JpaCalendarRepository.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/controller/CalendarController.java
  eeos/src/main/java/com/blackcompany/eeos/program/presentation/dto/UpdateCalendarRequest.java
Labels: feature

#241 [REFACTOR] 출석 현황 리스트 조회 / 출석 요약 정보 조회시 Calendar 적용
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
Labels: feature, 🔧refactor

#244 [FIX] 나의 출석 현황 리스트 조회 오류를 해결합니다.
  eeos/src/main/java/com/blackcompany/eeos/target/application/repository/AttendRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendRepository.java
Labels: bug

#245 [FIX] 나의 출석 현황 리스트 조회 오류 수정
  eeos/src/main/java/com/blackcompany/eeos/target/application/repository/AttendRepository.java
  eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendService.java
  eeos/src/main/java/com/blackcompany/eeos/target/persistence/AttendRepository.java
Labels: bug
